baseURL = "https://mohandacherir.github.io/Qdiv7/"
defaultContentLanguage = "en"
# Automatically generate robots.txt
enableRobotsTXT = true
languageCode = "en"
summaryLength = 36
theme = "risotto"
title = "Moe's VR blog"

[menu]
  [[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 1

  [[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 2
    
  [[menu.main]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/MohandAcherir"
    weight = 3

[params]
  description = "Writeups on kernel exploitation, Linux internals, cryptography, and vulnerability research."
  bio = """
Kernel exploitation, Linux internals, cryptography, and vulnerability research.
"""
  profilePhoto = "images/0074.png"
  socialCardImage = "images/scudo/Screenshot-2.png"
  xHandle = "@AcherirMoe"
  dateFormat = "January 2, 2006"

  [params.about]
    title = "Moe's VR blog"
    description = "Security Research Enthusiast: Kernels, Hypervisors, or anything worth exploring."

  [[params.social]]
    name = "GitHub"
    url = "https://github.com/MohandAcherir"

  [[params.social]]
    name = "X"
    url = "https://x.com/AcherirMoe/"

  [[params.social]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/mohand-a-acherir-b42911264/"
